-- Create coconut_plantations view that mirrors coconut_submissions table
-- This allows the frontend to query coconut_plantations while using the existing data

CREATE OR REPLACE VIEW coconut_plantations AS
SELECT 
  id,
  id as farmer_code,  -- Use id as farmer_code for compatibility
  id as farmer_id,    -- Use id as farmer_id for compatibility  
  farmer_name,
  phone,
  aadhaar,
  agent_name,
  active_status,
  total_area_hectares,
  area_under_coconut_hectares,
  number_of_plots,
  state,
  district,
  block_tehsil_mandal,
  village,
  date_of_plantation,
  spacing,
  seedlings_planted,
  seedlings_survived,
  plots,
  mapped_area_acres,
  location,
  created_at,
  created_by,
  land_ownership,
  land_use_before_plantation,
  tree_clearance_before_plantation,
  burning_trees_for_site_preparation,
  age_of_sapling_months,
  land_patta_survey_number,
  plantation_model,
  source_of_nursery,
  type_of_variety,
  size_of_pit,
  mode_of_irrigation,
  kharif_crop,
  kharif_crop_duration_days,
  rabi_crop,
  rabi_crop_duration_days,
  nitrogen_qty_kg,
  phosphorous_qty_kg,
  potassium_qty_kg,
  organic_qty_kg,
  other_qty_kg,
  cost_of_seedlings,
  fencing_propping_shading,
  land_preparation,
  manure_expenses,
  irrigation_expenses,
  weed_management,
  plant_protection,
  agriculture_implements,
  manpower_expenses,
  annual_fertilizers,
  annual_irrigations,
  annual_manpower
FROM coconut_submissions;
